spring:
  application:
    name: ai-service
  profiles:
    active: dev
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: ai-service-group
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: org.fitness.ai_service.model.entity.Activity
        spring.json.use.type.headers: false



server:
  port: 8072

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8090/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 10      # send heartbeat every 10 seconds
    lease-expiration-duration-in-seconds: 30
    hostname: localhost
